### ISSUE TITLE
User auth check

### ISSUE THREAD

**Issue by codedbyq** [codedbyq/CloudSound#2]
I finished user auth, can you review it for me?

**Comment by carlosaicrag** [comment]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [ ] Adequate and appropriate seeds

**Comment by carlosaicrag** [comment]
lets make it so we're able to click out of the modal when we click on the opacity background

**Comment by carlosaicrag** [comment]
let's remove the privacy and notification sections with the modal forms. we also want to remove any links that are not being used in the app such as the need help? and privacy policy links in the form

**Comment by carlosaicrag** [comment]
we need to add that logo on the navbar that will take you to "/" when you click on it

**Comment by carlosaicrag** [comment]
lets add the onclick handler to the entire div that is holding the element in the drop down.  For example i can't click login unless i actually click the word login.  we should be able to click if im in the same row as it

**Comment by carlosaicrag** [comment]
we need to have errors show on the forms

**Comment by carlosaicrag** [comment]
we should have a link on the forms that redirect us to the other form.  FOr example if we are in the signup form i want to have a link that takes me to the login form and vice versa

**Comment by carlosaicrag** [comment]
lets put the github and linked in links in the footer of your app

**Comment by carlosaicrag** [comment]
on the sign in form if i type an email and press enter it will sign me in.  We want to fix that so that you are only signed in when you type in both email and password

**Comment by codedbyq** [comment]
Finished each of the suggested changes, pushing to heroku now
